import Head from "next/head";

import Banner from "../components/Banner";
import Categories from "../components/Categories";
import Products from "../components/Products";
import FooterBanner from "../components/FooterBanner";

import { client } from "../lib/client";

export default function Home({ bannerData, categories, products }) {
  return (
    <>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner bannerData={bannerData} />
        <Categories categories={categories} />
        <Products products={products} />
        <FooterBanner />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const bannerQuery = '*[_type == "bannerInfo"]';
  const categoriesQuery = '*[_type == "category"]';
  const productsQuery =
    '*[_type == "product"][0..6]{ name ,price, image, desc, rating, slug, _id, category->{name,slug}}';

  const bannerData = await client.fetch(bannerQuery);
  const categories = await client.fetch(categoriesQuery);
  const products = await client.fetch(productsQuery);

  return {
    props: {
      bannerData: bannerData[0],
      categories,
      products,
    },
  };
};
